version: '3.8'

services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: playlist_app
      POSTGRES_PASSWORD: playlist_app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres-data: